name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b28005e52d6440995f3a70310391e814f82ae0dae5f06153b4ced503001003b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
