name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd27512f21b2fc2498e5db9374406642bfc9ffbc0223756febaec2ecb178aea7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
