name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac93c4d943458ba64fe2fab7fcbd5544ed852f6a9788a687f3a5ba329296e4a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
