name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfbf6978fd4f6361f93c06f13b10cba38c03f2e63ddbf1e829e26ff26f8fea92"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
