name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e8578febd0bd3705632317c48ab15037e19ad7f53ef2d5cd4219999b7f76dc7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
