name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af8d7a4e427a55a3e10c7ea40089348436440cb5ae4a3a9ca10acb5931b596c1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
