name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e4c231dabdb445e636d847f4e7ada65301eaeaa17acbbf4cd713e70c0c00287"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
