name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "426d2e33e05b3f0fd50a8103caeafd25ed9e9417612d225ce728f3778fa97a95"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
